services:
  database:
    build:
      context: ./database
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=inventory
    ports:
      - "4000:3306"
    networks:
      - myNetwork
  inventory_service:
    build:
      context: ./backend-nest
    container_name: inventory_service
    ports:
      - "5000:5000"
    command: bash -c "npx prisma generate && npm run start"
    depends_on:
      - database
    networks:
      - myNetwork
  webserver:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - inventory_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/ssl:/cert
    networks:
      - myNetwork
networks:
  myNetwork:
    driver: bridge
